### ISSUE TITLE
expiry

### ISSUE THREAD

**Issue by CrabbyPete** [awslabs/amazon-ecs-local-container-endpoints#32]
I am running this trying to use sms, but I get the following when I run docker-compose up
File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
app_1                  |     aws_session_token=aws_session_token, config=config)
app_1                  |   File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 826, in create_client
app_1                  |     credentials = self.get_credentials()
app_1                  |   File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 425, in get_credentials
app_1                  |     'credential_provider').load_credentials()
app_1                  |   File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1688, in load_credentials
app_1                  |     creds = provider.load()
app_1                  |   File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1551, in load
app_1                  |     return self._retrieve_or_fail()
app_1                  |   File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1566, in _retrieve_or_fail
app_1                  |     expiry_time=_parse_if_needed(creds['expiry_time']),
app_1                  |   File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 137, in _parse_if_needed
app_1                  |     return parse(value)
app_1                  |   File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1358, in parse
app_1                  |     return DEFAULTPARSER.parse(timestr, **kwargs)
app_1                  |   File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 652, in parse
app_1                  |     raise ValueError("String does not contain a date:", timestr)
app_1                  | ValueError: ('String does not contain a date:', '')
app_1                  | unable to load app 0 (mountpoint='') (callable not found or import error)

**Comment by gvwirth** [comment]
Getting the same error: `
root@b9e920735ee5:/# aws --debug s3 ls

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 208, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python3/dist-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/subcommands.py", line 465, in _run_main
    super(ListCommand, self)._run_main(parsed_args, parsed_globals)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/subcommands.py", line 451, in _run_main
    parsed_globals.verify_ssl)
  File "/usr/lib/python3/dist-packages/awscli/customizations/s3/subcommands.py", line 444, in get_client
    config=config)
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 850, in create_client
    credentials = self.get_credentials()
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 474, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/lib/python3/dist-packages/botocore/credentials.py", line 1662, in load_credentials
    creds = provider.load()
  File "/usr/lib/python3/dist-packages/botocore/credentials.py", line 1525, in load
    return self._retrieve_or_fail()
  File "/usr/lib/python3/dist-packages/botocore/credentials.py", line 1540, in _retrieve_or_fail
    expiry_time=_parse_if_needed(creds['expiry_time']),
  File "/usr/lib/python3/dist-packages/botocore/credentials.py", line 139, in _parse_if_needed
    return parse(value)
  File "/usr/lib/python3/dist-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python3/dist-packages/dateutil/parser.py", line 562, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
2019-12-04 17:14:54,682 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

String does not contain a date.`

The JSON output of the metadata endpoint is: 

`{"AccessKeyId":"<KEY>","Expiration":"","RoleArn":"","SecretAccessKey":"<SECRET>","Token":"<TOKEN>"}`

**Comment by PettitWesley** [comment]
I believe this was fixed by #28 

See #23 and #26 

We need to release the image- we will do this sometime next week.

**Comment by PettitWesley** [comment]
I'm planning to release the fix this week.

**Comment by PettitWesley** [comment]
Should be fixed in 1.1.0!
